env:
  browser: true
  commonjs: true
  es2021: true
extends: [airbnb-base]
overrides: []
parserOptions:
  ecmaVersion: latest
plugins: []
rules:
  arrow-body-style: [off, as-needed]
  brace-style: [warn, 1tbs]
  class-methods-use-this: [warn]
  comma-dangle: [warn]
  consistent-return: [warn]
  curly: [error, all]
  eqeqeq: [error, smart]
  func-names: [warn]
  import/extensions: [warn, ignorePackages]
  import/no-cycle: [warn]
  import/no-relative-packages: [warn]
  import/no-useless-path-segments: [off]
  import/prefer-default-export: [warn]
  max-classes-per-file: [off]
  max-len: [warn, 80, { ignoreComments: true, ignoreTrailingComments: true, ignoreUrls: true, ignoreStrings: true, ignoreTemplateLiterals: true }]
  no-alert: [warn]
  no-await-in-loop: [warn]
  no-debugger: [warn]
  no-multi-assign: [warn]
  no-param-reassign: [error, { props: false }]
  no-plusplus: [warn]
  no-restricted-syntax: [error, ForInStatement, LabeledStatement, WithStatement]
  no-return-assign: [error, except-parens]
  no-return-await: [warn]
  no-shadow: [error, { hoist: 'all', allow: ['resolve', 'reject', 'done', 'next', 'err', 'error'] }]
  no-underscore-dangle: [warn]
  no-unused-expressions: [warn, { allowTaggedTemplates: true, allowShortCircuit: true, allowTernary: true }]
  no-unused-vars: [warn, { ignoreRestSiblings: true, argsIgnorePattern: 'res|next|^err|^_', varsIgnorePattern: '^_' }]
  no-use-before-define: [warn]
  no-var: [off]
  prefer-const: [error, { destructuring: all }]
  prefer-destructuring: [warn]
  quotes: [error, 'double', { avoidEscape: true, allowTemplateLiterals: true }]
  semi: [error, always]
  space-before-function-paren: [warn]
  vars-on-top: [off]